### ISSUE TITLE
3.2.0 with docker error

### ISSUE THREAD

**Issue by hi-reeve** [victorgarciaesgi/nuxt-typed-router#94]
tried updating to latest 3.2.0 but when running build on docker i got an error javascript heap out of memory.
with 3.1.4 it has no problem

**Comment by hi-reeve** [comment]
> Weird, didn't even change the core. Can you provide more details?

probably this related to nuxt, because this also happen updating a few of nuxt official deps and the nuxt itself to 3.4.3
haven't dig into this deeper. for now i pin all the related modules to the non error version.

**Comment by szulcus** [comment]
I got these errors after upgrading from `^3.1.5` to `^3.2.2` (nuxt `^3.4.3`) 🤔
![image](https://github.com/victorgarciaesgi/nuxt-typed-router/assets/48328739/d5d8657a-6a19-44ec-b8c7-f293e4d365a5)
```
 ERROR  ✖ Error while formatting the output                                                                                                                                                              16:57:12  
SyntaxError: ';' expected. (23:8)
  21 |
  22 |
> 23 |   type ValidStringPath<T> = T extends ${string} ${string} ? false : T extends '' ? false : true;
     |        ^
  24 |
  25 |   type ValidParam<T, R extends boolean = true> = T extends ${infer A}/${infer B}
  26 |   ? A extends ${string} ${string}


 ERROR  Cannot start nuxt:  ';' expected. (23:8)                                                                                                                                                         16:57:12  
  21 |
  22 |
> 23 |   type ValidStringPath<T> = T extends ${string} ${string} ? false : T extends '' ? false : true;
     |        ^
  24 |
  25 |   type ValidParam<T, R extends boolean = true> = T extends ${infer A}/${infer B}
  26 |   ? A extends ${string} ${string}

    21 |
    22 |
  > 23 |   type ValidStringPath<T> = T extends ${string} ${string} ? false : T extends '' ? false : true;
       |        ^
    24 |
    25 |   type ValidParam<T, R extends boolean = true> = T extends ${infer A}/${infer B}
    26 |   ? A extends ${string} ${string}
  at v (node_modules\prettier\parser-typescript.js:1:14679)
  at _H (node_modules\prettier\parser-typescript.js:49:10722)
  at Object.cH [as parse] (node_modules\prettier\parser-typescript.js:49:11028)
  at Object.parse (node_modules\prettier\index.js:7515:23)
  at coreFormat (node_modules\prettier\index.js:8829:18)
  at formatWithCursor2 (node_modules\prettier\index.js:9021:18)
  at node_modules\prettier\index.js:38183:12
  at format (node_modules\prettier\index.js:38197:12)
  at formatOutputWithPrettier (/C:/Users/Jakub%20Schulz/Desktop/PRACA/SAT-TECH%20sp.%20z%20o.o/follow24-app/node_modules/nuxt-typed-router/dist/module.mjs:1255:30)
  at async processPathAndWriteFile (/C:/Users/Jakub%20Schulz/Desktop/PRACA/SAT-TECH%20sp.%20z%20o.o/follow24-app/node_modules/nuxt-typed-router/dist/module.mjs:1277:29)


 ERROR  [unhandledRejection] ';' expected. (23:8)                                                                                                                                                        16:57:12  
  21 |
  22 |
> 23 |   type ValidStringPath<T> = T extends ${string} ${string} ? false : T extends '' ? false : true;
     |        ^
  24 |
  25 |   type ValidParam<T, R extends boolean = true> = T extends ${infer A}/${infer B}
  26 |   ? A extends ${string} ${string}

    21 |
    22 |
  > 23 |   type ValidStringPath<T> = T extends ${string} ${string} ? false : T extends '' ? false : true;
       |        ^
    24 |
    25 |   type ValidParam<T, R extends boolean = true> = T extends ${infer A}/${infer B}
    26 |   ? A extends ${string} ${string}
  at v (node_modules\prettier\parser-typescript.js:1:14679)
  at _H (node_modules\prettier\parser-typescript.js:49:10722)
  at Object.cH [as parse] (node_modules\prettier\parser-typescript.js:49:11028)
  at Object.parse (node_modules\prettier\index.js:7515:23)
  at coreFormat (node_modules\prettier\index.js:8829:18)
  at formatWithCursor2 (node_modules\prettier\index.js:9021:18)
  at node_modules\prettier\index.js:38183:12
  at format (node_modules\prettier\index.js:38197:12)
  at formatOutputWithPrettier (/C:/Users/Jakub%20Schulz/Desktop/PRACA/SAT-TECH%20sp.%20z%20o.o/follow24-app/node_modules/nuxt-typed-router/dist/module.mjs:1255:30)
  at async processPathAndWriteFile (/C:/Users/Jakub%20Schulz/Desktop/PRACA/SAT-TECH%20sp.%20z%20o.o/follow24-app/node_modules/nuxt-typed-router/dist/module.mjs:1277:29)


 ERROR  ✖ Error while formatting the output                                                                                                                                                              16:57:12  
SyntaxError: ';' expected. (19:12)
  17 |    * */
  18 |   export type RoutesNamesList =
> 19 |     export type WithoutBracket<T extends string> = T extends :${string} ? never : T;
     |            ^
  20 |
  21 |
  22 |   /**
```

**Comment by szulcus** [comment]
@victorgarciaesgi https://stackblitz.com/edit/github-7e4xvw-jpx4fm?file=package.json

**Comment by victorgarciaesgi** [comment]
Your defautLocale isn't matching any of your locales code
https://stackblitz.com/edit/github-7e4xvw-9ajhl9?file=nuxt.config.ts,.nuxt%2Ftyped-router%2F__i18n-router.ts

**Comment by szulcus** [comment]
I don't know what it is, but I still have this error 🤔
![image](https://github.com/victorgarciaesgi/nuxt-typed-router/assets/48328739/dcdad395-e027-4fef-a399-83e2f9ccebc3)

**Comment by victorgarciaesgi** [comment]
Prettier is used to format the output, if it fails it's because the output is not valid typescript

**Comment by szulcus** [comment]
@victorgarciaesgi Oh shit... I think it's time to take a break from the computer 😅. Now everything works. Thank you very much for help! ❤️
